### ISSUE TITLE
empty string codec error

### ISSUE THREAD

**Issue by chrislusf** [glycerine/truepack#1]
The test will be failing of line 13 is changed to empty strings.

https://github.com/chrislusf/gleam/blob/master/util/row_read_write_test.go#L13

There are bugs reported:

https://github.com/chrislusf/gleam/issues/90
https://github.com/chrislusf/gleam/issues/88

**Comment by glycerine** [comment]
Thanks for reporting. Should be fixed with 58d269be15e0b86108f95f332f8a0194cea243aa . Let me know.

**Comment by glycerine** [comment]
@chrislusf Also I note in passing: you probably don't want to be using the unsafe string stuff here, as you probably can't guarantee the pre-conditions for correctness in the dynamic context of gleam.
